Specifying Database TABLESPACES as 'pg_default' for all HES Dataset Tables and Indices.
oxford-pharmacoepi/etl_ndorms pull request #22
Opened 2024-01-15 15:27 UTC by Mandickel

2024-01-16 14:35 UTC, adelmestri requested changes
Hi Mandi,
the creation files are fine, but in all the indexes files, you have updated only the PK, not the secondary indexes. Have a look at some examples (those starting with "5_* and update

2024-01-16 14:38 UTC, Mandickel commented
> Hi Mandi, the creation files are fine, but in all the indexes files, you have updated only the PK, not the secondary indexes. Have a look at some examples (those starting with "5_* and update

Alright, updating.

2024-01-17 00:09 UTC, adelmestri approved these changes

2024-01-17 00:11 UTC, adelmestri approved these changes

2024-01-17 00:11 UTC, merged